from advent_of_code.day_1  import DayOne
from advent_of_code.day_2  import DayTwo
from advent_of_code.day_3  import DayThree
from advent_of_code.day_4  import DayFour
from advent_of_code.day_5  import DayFive
from advent_of_code.day_6  import DaySix
from advent_of_code.day_7  import DaySeven
from advent_of_code.day_8  import DayEight
from advent_of_code.day_9  import DayNine
from advent_of_code.day_10 import DayTen
from advent_of_code.day_11 import DayEleven
from advent_of_code.day_12 import DayTwelve